In [1]:
import pandas as pd

df = pd.read_csv("data/projections_20202021.csv")

In [2]:
#data frame object - sort of like a table

df

,player_id,name,position,goals,assists,points,shots,timeOnIcePerGame
0,8478402,Connor McDavid,C,26,48,74,173,20.78
1,8477934,Leon Draisaitl,C,29,43,72,160,21.35
2,8476453,Nikita Kucherov,RW,24,41,65,158,18.11
3,8477492,Nathan MacKinnon,C,25,39,64,233,20.22
4,8478550,Artemi Panarin,LW,21,42,63,150,19.47
...,...,...,...,...,...,...,...,...
505,8475625,Matt Irwin,D,0,6,6,77,13.71
506,8474134,Yannick Weber,D,1,4,5,60,13.40
507,8474568,Luke Schenn,D,1,4,5,62,12.35
508,8474230,Micheal Haley,C,2,2,4,33,6.23
509,8470318,Jonathan Ericsson,D,0,2,2,48,14.12

In [3]:
df['assists'].max()

np.int64(48)

In [4]:
#df.loc['assists'].max()

In [5]:
# retrieve the names of players that have goals over 20
df[df['goals'] > 20]['name']

0       Connor McDavid
1       Leon Draisaitl
2      Nikita Kucherov
3     Nathan MacKinnon
4       Artemi Panarin
5       David Pastrnak
7       Mika Zibanejad
9      Auston Matthews
10        Patrick Kane
12         Jack Eichel
14      Steven Stamkos
16      Mark Scheifele
17      Mikko Rantanen
18       Jake Guentzel
19       Brayden Point
22       Alex Ovechkin
23       Sebastian Aho
24         Kyle Connor
28        John Tavares
29    Patrice Bergeron
39        Patrik Laine
40          Bryan Rust
61        Evander Kane
Name: name, dtype: object

In [6]:
# retrieve the names of players that have goals under 20
df[['name','goals']][df['goals'] < 20]

                   name  goals
8       Mitchell Marner     16
13        Sidney Crosby     19
15   Jonathan Huberdeau     18
20    Aleksander Barkov     17
21           Mark Stone     19
..                  ...    ...
505          Matt Irwin      0
506       Yannick Weber      1
507         Luke Schenn      1
508       Micheal Haley      2
509   Jonathan Ericsson      0

[482 rows x 2 columns]

In [7]:
#What is average number of goals for players in position D?
df.loc[df['position'] == 'D']['goals'].mean()

np.float64(3.6123595505617976)

In [8]:
df.head()

,player_id,name,position,goals,assists,points,shots,timeOnIcePerGame
0,8478402,Connor McDavid,C,26,48,74,173,20.78
1,8477934,Leon Draisaitl,C,29,43,72,160,21.35
2,8476453,Nikita Kucherov,RW,24,41,65,158,18.11
3,8477492,Nathan MacKinnon,C,25,39,64,233,20.22
4,8478550,Artemi Panarin,LW,21,42,63,150,19.47

In [9]:
# Similar to SQL group by SELECT * FROM ons_20202021 GROUP BY position; 
df_grouped = df.groupby('position')

df_grouped

In [10]:
for position, position_df in df_grouped:
    print(position)
    print(position_df)
    print()

C
     player_id              name position  goals  assists  points  shots  \
0      8478402    Connor McDavid        C     26       48      74    173
1      8477934    Leon Draisaitl        C     29       43      72    160
3      8477492  Nathan MacKinnon        C     25       39      64    233
6      8471215     Evgeni Malkin        C     20       40      60    153
7      8476459    Mika Zibanejad        C     30       29      59    180
..         ...               ...      ...    ...      ...     ...    ...
452    8476440   Markus Granlund        C      6        5      11     57
455    8474291        Jay Beagle        C      3        8      11     53
460    8474736       Zac Rinaldo        C      6        5      11     51
464    8477213      Tim Schaller        C      5        5      10     57
508    8474230     Micheal Haley        C      2        2       4     33

     timeOnIcePerGame
0               20.78
1               21.35
3               20.22
6               18.50
7               20.36
..                ...
452             11.17
455             12.42
460              8.33
464             11.32
508              6.23

[157 rows x 8 columns]

D
     player_id               name position  goals  assists  points  shots  \
31     8474590       John Carlson        D      9       38      47    132
60     8474600         Roman Josi        D      9       30      39    180
74     8476792         Torey Krug        D      6       32      38    118
79     8470613        Brent Burns        D      8       29      37    163
81     8475167      Victor Hedman        D      7       30      37    122
..         ...                ...      ...    ...      ...     ...    ...
504    8474090      Brendan Smith        D      1        5       6     44
505    8475625         Matt Irwin        D      0        6       6     77
506    8474134      Yannick Weber        D      1        4       5     60
507    8474568        Luke Schenn        D      1        4       5     62
509    8470318  Jonathan Ericsson        D      0        2       2     48

     timeOnIcePerGame
31              23.21
60              24.14
74              19.59
79              23.84
81              22.20
..                ...
504             11.41
505             13.71
506             13.40
507             12.35
509             14.12

[178 rows x 8 columns]

LW
     player_id                name position  goals  assists  points  shots  \
4      8478550      Artemi Panarin       LW     21       42      63    150
11     8473419       Brad Marchand       LW     20       39      59    139
15     8476456  Jonathan Huberdeau       LW     18       37      55    127
22     8471214       Alex Ovechkin       LW     31       18      49    217
24     8478398         Kyle Connor       LW     25       24      49    172
..         ...                 ...      ...    ...      ...     ...    ...
458    8476948       Charles Hudon       LW      5        6      11     83
470    8474709         Matt Martin       LW      5        5      10     53
488    8471716   Justin Abdelkader       LW      2        6       8     55
496    8476207       Brian Gibbons       LW      3        4       7     42
501    8475268     Gabriel Bourque       LW      2        5       7     41

     timeOnIcePerGame
4               19.47
11              18.52
15              17.90
22              19.62
24              19.80
..                ...
458             11.40
470             10.48
488             11.77
496              9.90
501              8.86

[101 rows x 8 columns]

RW
     player_id             name position  goals  assists  points  shots  \
2      8476453  Nikita Kucherov       RW     24       41      65    158
5      8477956   David Pastrnak       RW     30       32      62    201
10     8474141     Patrick Kane       RW     23       36      59    200
17     8478420   Mikko Rantanen       RW     21       32      53    140
21     8475913       Mark Stone       RW     19       31      50    135
..         ...              ...      ...    ...      ...     ...    ...
422    8476439    Brett Ritchie       RW      5        7      12     69
433    8471817      Ryan Reaves       RW      5        7      12     55
463    8474668       Dale Weise       RW      3        7      10     47
471    8471426     Troy Brouwer       RW      6        4      10     53
477    8477401      John Hayden       RW      5        4       9     55

     timeOnIcePerGame
2               18.11
5               18.10
10              20.32
17              18.38
21              18.48
..                ...
422             10.28
433             10.17
463              9.59
471              9.90
477              9.69

[74 rows x 8 columns]

In [11]:
df_grouped.get_group('D')

,player_id,name,position,goals,assists,points,shots,timeOnIcePerGame
31,8474590,John Carlson,D,9,38,47,132,23.21
60,8474600,Roman Josi,D,9,30,39,180,24.14
74,8476792,Torey Krug,D,6,32,38,118,19.59
79,8470613,Brent Burns,D,8,29,37,163,23.84
81,8475167,Victor Hedman,D,7,30,37,122,22.20
...,...,...,...,...,...,...,...,...
504,8474090,Brendan Smith,D,1,5,6,44,11.41
505,8475625,Matt Irwin,D,0,6,6,77,13.71
506,8474134,Yannick Weber,D,1,4,5,60,13.40
507,8474568,Luke Schenn,D,1,4,5,62,12.35
509,8470318,Jonathan Ericsson,D,0,2,2,48,14.12

In [12]:
df_grouped.max()

,player_id,name,goals,assists,points,shots,timeOnIcePerGame
position,,,,,,,
C,8480144,Zemgus Girgensons,33,48,74,233,21.35
D,8480172,Zdeno Chara,13,38,47,180,24.31
LW,8479465,Zack Smith,31,42,63,217,19.80
RW,8479339,Zack Kassian,30,41,65,201,20.32

In [13]:
group_position = (
    df
    .groupby('position')
    .max()
)

group_position

,player_id,name,goals,assists,points,shots,timeOnIcePerGame
position,,,,,,,
C,8480144,Zemgus Girgensons,33,48,74,233,21.35
D,8480172,Zdeno Chara,13,38,47,180,24.31
LW,8479465,Zack Smith,31,42,63,217,19.80
RW,8479339,Zack Kassian,30,41,65,201,20.32

In [14]:
group_position = (
    df
    #.groupby(['position','points','name'])['timeOnIcePerGame']
    .groupby(['position','name'])['timeOnIcePerGame']
    .max()
)

group_position

position  name
C         Adam Henrique        16.14
          Adam Lowry           14.43
          Aleksander Barkov    19.25
          Alex Iafallo         17.83
          Alexander Kerfoot    14.30
                               ...
RW        Tom Kuhnhackl        11.31
          Tom Wilson           17.40
          Troy Brouwer          9.90
          Wayne Simmonds       14.50
          Zack Kassian         15.01
Name: timeOnIcePerGame, Length: 510, dtype: float64

In [15]:
# find the average time on ice per game for players who are defence men
group_position = (
    df
    .groupby(['position','points','name'])['timeOnIcePerGame']
    .mean()
    .sort_values(ascending=False)
)

group_position

position  points  name
D         26      Drew Doughty       24.31
          32      Thomas Chabot      24.23
          35      Kris Letang        24.18
          39      Roman Josi         24.14
          37      Brent Burns        23.84
                                     ...
RW        10      Dale Weise          9.59
LW        7       Gabriel Bourque     8.86
C         11      Zac Rinaldo         8.33
LW        11      Ross Johnston       8.18
C         4       Micheal Haley       6.23
Name: timeOnIcePerGame, Length: 510, dtype: float64

In [16]:
group_name = (
    df
    .groupby(['name'])['timeOnIcePerGame']
    .max()


)

group_name

name
Aaron Ekblad         21.75
Adam Erne            11.51
Adam Henrique        16.14
Adam Larsson         19.03
Adam Lowry           14.43
                     ...
Zach Werenski        22.48
Zack Kassian         15.01
Zack Smith           12.06
Zdeno Chara          19.82
Zemgus Girgensons    13.40
Name: timeOnIcePerGame, Length: 510, dtype: float64

In [17]:
df.head()

,player_id,name,position,goals,assists,points,shots,timeOnIcePerGame
0,8478402,Connor McDavid,C,26,48,74,173,20.78
1,8477934,Leon Draisaitl,C,29,43,72,160,21.35
2,8476453,Nikita Kucherov,RW,24,41,65,158,18.11
3,8477492,Nathan MacKinnon,C,25,39,64,233,20.22
4,8478550,Artemi Panarin,LW,21,42,63,150,19.47

In [18]:
# Group players by 'goals scored'
grouped = df.groupby('goals')

# Loop through groups and display
for goals, group in grouped:
    print(f"goals: {goals}")
    print(group)
    print("_" * 40)

goals: 0
     player_id               name position  goals  assists  points  shots  \
483    8471729       Kris Russell        D      0        8       8     48
492    8475324        Nick Jensen        D      0        8       8     55
493    8473415         Alex Biega        D      0        8       8     75
495    8474688       Greg Pateryn        D      0        7       7     61
499    8475868    Anthony Bitetto        D      0        7       7     57
500    8469465        Dan Hamhuis        D      0        7       7     41
502    8471392        Roman Polak        D      0        6       6     50
505    8475625         Matt Irwin        D      0        6       6     77
509    8470318  Jonathan Ericsson        D      0        2       2     48

     timeOnIcePerGame
483             16.47
492             17.18
493             15.90
495             15.09
499             14.32
500             14.22
502             16.25
505             13.71
509             14.12
________________________________________
goals: 1
     player_id                name position  goals  assists  points  shots  \
403    8476331        Dylan DeMelo        D      1       12      13     72
408    8474584   Michael Del Zotto        D      1       12      13     64
413    8475690   Christopher Tanev        D      1       12      13     45
418    8475455      Brenden Dillon        D      1       11      12     52
435    8475462         Radko Gudas        D      1       11      12     78
437    8474027        Justin Braun        D      1       11      12     63
442    8474567       Zach Bogosian        D      1       10      11     66
443    8474218        Jason Demers        D      1       10      11     61
451    8472382         Andy Greene        D      1       10      11     58
459    8468493         Ron Hainsey        D      1       10      11     47
466    8475233        David Savard        D      1        9      10     78
475    8474818         Jordie Benn        D      1        8       9     66
478    8471686          Marc Staal        D      1        8       9     53
479    8470187      Johnny Boychuk        D      1        8       9     84
480    8475179      Dmitry Kulikov        D      1        8       9     57
481    8470151     Jay Bouwmeester        D      1        8       9     56
482    8470110        Trevor Daley        D      1        7       8     50
484    8471769  Niklas Hjalmarsson        D      1        7       8     42
485    8471677        Jack Johnson        D      1        7       8     56
486    8470601      Braydon Coburn        D      1        7       8     62
487    8468674     Deryk Engelland        D      1        7       8     66
491    8471284       Andrej Sekera        D      1        7       8     62
494    8475762       Derek Forbort        D      1        6       7     58
498    8474145     Robert Bortuzzo        D      1        6       7     52
503    8473560    Korbinian Holzer        D      1        5       6     46
504    8474090       Brendan Smith        D      1        5       6     44
506    8474134       Yannick Weber        D      1        4       5     60
507    8474568         Luke Schenn        D      1        4       5     62

     timeOnIcePerGame
403             19.04
408             17.68
413             18.64
418             18.42
435             16.16
437             16.82
442             16.61
443             19.39
451             18.72
459             19.57
466             19.52
475             15.85
478             17.06
479             16.71
480             18.58
481             20.33
482             15.38
484             17.98
485             18.50
486             13.85
487             17.04
491             16.96
494             17.32
498             13.01
503             15.43
504             11.41
506             13.40
507             12.35
________________________________________
goals: 2
     player_id                 name position  goals  assists  points  shots  \
248    8470281         Duncan Keith        D      2       20      22     93
321    8474581        Jake Gardiner        D      2       16      18     66
324    8474151        Ryan McDonagh        D      2       15      17     67
331    8477969    Marcus Pettersson        D      2       15      17     66
341    8476525         Colin Miller        D      2       14      16     86
345    8476422          Mike Reilly        D      2       14      16     97
360    8475208       Brian Dumoulin        D      2       13      15     71
368    8474013             Ian Cole        D      2       13      15     69
378    8479482        Michal Kempny        D      2       12      14     73
380    8471873       Anton Stralman        D      2       12      14     69
388    8476917          Adam Pelech        D      2       12      14     76
392    8476312          Josh Manson        D      2       11      13     71
402    8475177       Calvin de Haan        D      2       11      13     78
421    8476470      Nathan Beaulieu        D      2       10      12     61
427    8476449     Scott Harrington        D      2       10      12     51
430    8479458       Nikita Zaitsev        D      2       10      12     61
444    8476988         Matt Benning        D      2        9      11     55
445    8480172            Jan Rutta        D      2        9      11     66
446    8476967          Brett Kulak        D      2        9      11     93
448    8475747        Patrik Nemeth        D      2        9      11     71
450    8475841             Tim Heed        D      2        9      11     60
456    8477046          Joakim Ryan        D      2        9      11     76
462    8477509        Mirco Mueller        D      2        8      10     41
469    8475188       Brayden McNabb        D      2        8      10     60
472    8476457         Adam Larsson        D      2        8      10     71
473    8477845  Trevor van Riemsdyk        D      2        8      10     66
476    8480147     Oscar Fantenberg        D      2        7       9     66
488    8471716    Justin Abdelkader       LW      2        6       8     55
489    8477850      Christian Folin        D      2        6       8     50
497    8477244        Chad Ruhwedel        D      2        5       7     59
501    8475268      Gabriel Bourque       LW      2        5       7     41
508    8474230        Micheal Haley        C      2        2       4     33

     timeOnIcePerGame
248             22.81
321             16.45
324             19.96
331             18.19
341             16.67
345             17.28
360             19.95
368             17.10
378             17.86
380             19.90
388             19.77
392             19.74
402             18.78
421             16.15
427             13.46
430             20.77
444             13.08
445             15.03
446             16.50
448             20.28
450             12.84
456             17.58
462             16.92
469             18.95
472             19.03
473             14.40
476             15.33
488             11.77
489             14.11
497             14.44
501              8.86
508              6.23
________________________________________
goals: 3
     player_id                 name position  goals  assists  points  shots  \
146    8471735         Keith Yandle        D      3       27      30    100
235    8479398        Samuel Girard        D      3       20      23     80
263    8471274       Alex Goligoski        D      3       18      21     77
270    8474031    Kevin Shattenkirk        D      3       17      20     97
273    8475200         Dmitry Orlov        D      3       17      20     80
285    8477355         Will Butcher        D      3       17      20     66
286    8476850          Ryan Murray        D      3       17      20     67
299    8476463         Jonas Brodin        D      3       16      19     80
302    8475181           Nick Leddy        D      3       16      19     70
327    8474602       Justin Schultz        D      3       14      17     92
336    8471242           Mike Green        D      3       14      17     88
342    8474673            TJ Brodie        D      3       13      16     61
343    8477474        Madison Bowey        D      3       13      16     69
346    8476891        Matt Grzelcyk        D      3       13      16     81
357    8474166        Alec Martinez        D      3       12      15     77
359    8476874          Olli Maatta        D      3       12      15     69
384    8473446         Erik Johnson        D      3       11      14     92
396    8479442         Troy Stecher        D      3       10      13     67
397    8477018           Ben Hutton        D      3       10      13     88
399    8471709  Marc-Edouard Vlasic        D      3       10      13     64
401    8476886      Slater Koekkoek        D      3       10      13     64
405    8477462          Robert Hagg        D      3       10      13     51
406    8477851      Jordan Oesterle        D      3       10      13     63
407    8476941       Connor Carrick        D      3       10      13     54
409    8478443        Brandon Carlo        D      3       10      13     89
411    8476879            Cody Ceci        D      3       10      13     64
415    8477464            Nic Petan       LW      3        9      12     67
420    8477938         Haydn Fleury        D      3        9      12     70
423    8476931          Jake McCabe        D      3        9      12     63
428    8479376          Victor Mete        D      3        9      12     60
441    8474612       Travis Hamonic        D      3        9      12     90
447    8475750          Jon Merrill        D      3        8      11     54
449    8474207          Nick Holden        D      3        8      11     81
455    8474291           Jay Beagle        C      3        8      11     53
457    8465009          Zdeno Chara        D      3        8      11     70
461    8470607       Brent Seabrook        D      3        7      10     78
463    8474668           Dale Weise       RW      3        7      10     47
465    8474125      Carl Gunnarsson        D      3        7      10     50
467    8476467       Jamie Oleksiak        D      3        7      10     61
468    8474618      Marco Scandella        D      3        7      10     67
474    8475790      Erik Gudbranson        D      3        7      10     78
490    8475186           John Moore        D      3        5       8     74
496    8476207        Brian Gibbons       LW      3        4       7     42

     timeOnIcePerGame
146             19.00
235             19.99
263             21.53
270             18.00
273             21.07
285             17.26
286             19.11
299             20.30
302             20.04
327             18.95
336             19.87
342             19.51
343             16.85
346             17.37
357             20.44
359             17.60
384             19.92
396             15.27
397             17.85
399             19.34
401             15.99
405             15.16
406             16.50
407             14.21
409             19.39
411             19.69
415             10.66
420             13.19
423             17.72
428             15.57
441             20.04
447             17.31
449             17.65
455             12.42
457             19.82
461             17.43
463              9.59
465             15.20
467             15.24
468             16.88
474             18.31
490             16.11
496              9.90
________________________________________
goals: 4
     player_id                 name position  goals  assists  points  shots  \
87     8474578        Erik Karlsson        D      4       32      36    125
150    8470600           Ryan Suter        D      4       26      30     85
175    8480145           Neal Pionk        D      4       23      27    121
185    8474563         Drew Doughty        D      4       22      26    106
194    8476472        Oscar Klefbom        D      4       22      26    136
209    8477499   Rasmus Ristolainen        D      4       21      25    104
264    8476854      Hampus Lindholm        D      4       17      21     99
294    8478396         Noah Hanifin        D      4       15      19     96
309    8477488          Brett Pesce        D      4       14      18     88
315    8476902          Esa Lindell        D      4       14      18     83
338    8474574          Tyler Myers        D      4       13      17    102
370    8473463          Leo Komarov        C      4       11      15     57
375    8478408       Travis Dermott        D      4       10      14     71
382    8476441       Joel Edmundson        D      4       10      14     78
386    8478906     Markus Nutivaara        D      4       10      14     68
387    8470655         David Backes       RW      4       10      14     80
393    8474697      Mark Borowiecki        D      4        9      13     65
395    8476894      Brendan Leipsic       LW      4        9      13     55
398    8476858  Phillip Di Giuseppe       LW      4        9      13     89
404    8476429       Scott Mayfield        D      4        9      13     78
414    8471699      Andrew Cogliano       LW      4        9      13     65
417    8474062           Riley Nash        C      4        8      12     60
425    8477507       Nikita Zadorov        D      4        8      12     64
429    8471743     Vladimir Sobotka       LW      4        8      12     75
434    8476356        Tobias Rieder        C      4        8      12     75
436    8470775        Nate Thompson        C      4        8      12     56
438    8475796           Mark Pysyk        D      4        8      12     54
440    8477455     Jacob de la Rose       LW      4        8      12     57

     timeOnIcePerGame
87              23.07
150             23.38
175             21.82
185             24.31
194             23.73
209             21.70
264             21.85
294             20.02
309             20.55
315             22.19
338             20.24
370             12.47
375             16.58
382             17.70
386             15.50
387              9.82
393             16.91
395              9.71
398             11.04
404             18.83
414             12.20
417             11.56
425             16.82
429             13.83
434             11.14
436             12.55
438             13.03
440             10.72
________________________________________
goals: 5
     player_id                name position  goals  assists  points  shots  \
193    8471303     Alexander Edler        D      5       21      26    105
202    8479325      Charlie McAvoy        D      5       20      25     87
205    8477504      Josh Morrissey        D      5       20      25     96
219    8476885        Jacob Trouba        D      5       19      24    118
225    8476958       Jaccob Slavin        D      5       19      24    107
229    8477498       Darnell Nurse        D      5       19      24    124
231    8475218      Mattias Ekholm        D      5       19      24    110
236    8475222        Sami Vatanen        D      5       18      23    106
245    8477505  Alexander Wennberg        C      5       17      22     71
247    8474162         Jake Muzzin        D      5       17      22     96
268    8471702       Matt Niskanen        D      5       15      20     92
297    8477986     Brandon Montour        D      5       14      19     92
313    8474056         P.K. Subban        D      5       13      18    119
320    8476869         Brady Skjei        D      5       13      18    101
325    8476473       Connor Murphy        D      5       12      17    101
344    8475753        Justin Faulk        D      5       11      16    113
351    8477846      Ryan Carpenter        C      5       11      16     74
366    8476921    Jordan Martinook       LW      5       10      15     67
369    8476779           Brad Hunt        D      5       10      15     90
371    8474571      Mikkel Boedker       LW      5       10      15     70
373    8474250          Zack Smith       LW      5        9      14     58
377    8474098     Colton Sceviour        C      5        9      14     94
389    8470144       Frans Nielsen        C      5        9      14     79
400    8473504     Cal Clutterbuck       RW      5        8      13     62
422    8476439       Brett Ritchie       RW      5        7      12     69
424    8473453        Trevor Lewis        C      5        7      12     89
432    8477454           Adam Erne       LW      5        7      12     67
433    8471817         Ryan Reaves       RW      5        7      12     55
453    8475807    Joakim Nordstrom       LW      5        6      11     65
454    8477527       Ross Johnston       LW      5        6      11     39
458    8476948       Charles Hudon       LW      5        6      11     83
464    8477213        Tim Schaller        C      5        5      10     57
470    8474709         Matt Martin       LW      5        5      10     53
477    8477401         John Hayden       RW      5        4       9     55

     timeOnIcePerGame
193             21.55
202             21.69
205             21.46
219             21.34
225             22.03
229             22.15
231             22.04
236             20.57
245             15.85
247             20.41
268             20.73
297             18.84
313             20.97
320             19.68
325             19.95
344             19.71
351             13.52
366             11.46
369             14.60
371             10.17
373             12.06
377             12.83
389             13.61
400             13.14
422             10.28
424             11.93
432             11.51
433             10.17
453             11.92
454              8.18
458             11.40
464             11.32
470             10.48
477              9.69
________________________________________
goals: 6
     player_id                      name position  goals  assists  points  \
74     8476792                Torey Krug        D      6       32      38
107    8476853             Morgan Rielly        D      6       28      34
126    8475197              Tyson Barrie        D      6       26      32
137    8475906            John Klingberg        D      6       25      31
142    8470966             Mark Giordano        D      6       24      30
154    8477495                Seth Jones        D      6       23      29
169    8477932              Aaron Ekblad        D      6       22      28
189    8477220              Nate Schmidt        D      6       20      26
212    8479410         Mikhail Sergachev        D      6       18      24
233    8475764                Cam Fowler        D      6       17      23
234    8476923            Damon Severson        D      6       17      23
239    8469459               Mikko Koivu        C      6       17      23
261    8476906       Shayne Gostisbehere        D      6       15      21
275    8477948            Travis Sanheim        D      6       14      20
281    8474176              Carl Hagelin       LW      6       14      20
300    8477406           Mattias Janmark        C      6       13      19
306    8476374               Sean Kuraly        C      6       12      18
307    8469455              Jason Spezza        C      6       12      18
310    8478407                Vince Dunn        D      6       12      18
314    8477346          MacKenzie Weegar        D      6       12      18
330    8476875             Mike Matheson        D      6       11      17
340    8475279               Ben Chiarot        D      6       11      17
347    8480144               David Kampf        C      6       10      16
348    8473473               Milan Lucic       LW      6       10      16
355    8475728             Johan Larsson        C      6       10      16
358    8477930  Pierre-Edouard Bellemare       LW      6        9      15
363    8477240             Carter Rowney       RW      6        9      15

In [19]:
grouped = (
    #df.groupby(['goals','name'])
    df.groupby(['goals'])
    #.mean() 


) 

grouped.get_group((21))

C:\Users\User\AppData\Local\Temp\ipykernel_55896\1167990876.py:9: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  grouped.get_group((21))

,player_id,name,position,goals,assists,points,shots,timeOnIcePerGame
4,8478550,Artemi Panarin,LW,21,42,63,150,19.47
17,8478420,Mikko Rantanen,RW,21,32,53,140,18.38
19,8478010,Brayden Point,C,21,30,51,123,17.99
40,8475810,Bryan Rust,RW,21,23,44,137,18.40
61,8475169,Evander Kane,LW,21,18,39,177,18.47

In [21]:
grouped = (
    #df.groupby(['goals','name'])
    df.groupby(['goals'])
    #.mean() 


) 

grouped.get_group((21))

C:\Users\User\AppData\Local\Temp\ipykernel_55896\1167990876.py:9: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  grouped.get_group((21))

,player_id,name,position,goals,assists,points,shots,timeOnIcePerGame
4,8478550,Artemi Panarin,LW,21,42,63,150,19.47
17,8478420,Mikko Rantanen,RW,21,32,53,140,18.38
19,8478010,Brayden Point,C,21,30,51,123,17.99
40,8475810,Bryan Rust,RW,21,23,44,137,18.40
61,8475169,Evander Kane,LW,21,18,39,177,18.47

In [30]:
df

,player_id,name,position,goals,assists,points,shots,timeOnIcePerGame
0,8478402,Connor McDavid,C,26,48,74,173,20.78
1,8477934,Leon Draisaitl,C,29,43,72,160,21.35
2,8476453,Nikita Kucherov,RW,24,41,65,158,18.11
3,8477492,Nathan MacKinnon,C,25,39,64,233,20.22
4,8478550,Artemi Panarin,LW,21,42,63,150,19.47
...,...,...,...,...,...,...,...,...
505,8475625,Matt Irwin,D,0,6,6,77,13.71
506,8474134,Yannick Weber,D,1,4,5,60,13.40
507,8474568,Luke Schenn,D,1,4,5,62,12.35
508,8474230,Micheal Haley,C,2,2,4,33,6.23
509,8470318,Jonathan Ericsson,D,0,2,2,48,14.12

In [31]:
group_by_frame = df.groupby('position', observed=True)

In [34]:
group_by_frame.mean(numeric_only=True)

,player_id,goals,assists,points,shots,timeOnIcePerGame
position,,,,,,
C,8.475739e+06,11.834395,17.280255,29.114650,104.082803,15.541656
D,8.475402e+06,3.612360,13.528090,17.140449,84.056180,18.707079
LW,8.475933e+06,11.099010,14.623762,25.722772,101.950495,14.248713
RW,8.475478e+06,12.567568,15.932432,28.500000,111.000000,14.939730

In [35]:
group_by_frame.mean(numeric_only=True).reset_index()

,position,player_id,goals,assists,points,shots,timeOnIcePerGame
0,C,8.475739e+06,11.834395,17.280255,29.114650,104.082803,15.541656
1,D,8.475402e+06,3.612360,13.528090,17.140449,84.056180,18.707079
2,LW,8.475933e+06,11.099010,14.623762,25.722772,101.950495,14.248713
3,RW,8.475478e+06,12.567568,15.932432,28.500000,111.000000,14.939730

In [38]:
group_by_frame = df.groupby('position', observed=True)
position_means = (
    group_by_frame.mean(numeric_only=True)
    .reset_index()
    .sort_values(by="points", ascending=False)
)

print(position_means)

  position     player_id      goals    assists     points       shots  \
0        C  8.475739e+06  11.834395  17.280255  29.114650  104.082803
3       RW  8.475478e+06  12.567568  15.932432  28.500000  111.000000
2       LW  8.475933e+06  11.099010  14.623762  25.722772  101.950495
1        D  8.475402e+06   3.612360  13.528090  17.140449   84.056180

   timeOnIcePerGame
0         15.541656
3         14.939730
2         14.248713
1         18.707079

In [45]:
group_by_frame = (
    df
    .groupby('position')
    .mean(numeric_only=True)
    .reset_index()
    .sort_values(by='points', ascending=False)

)
group_by_frame

,position,player_id,goals,assists,points,shots,timeOnIcePerGame
0,C,8.475739e+06,11.834395,17.280255,29.114650,104.082803,15.541656
3,RW,8.475478e+06,12.567568,15.932432,28.500000,111.000000,14.939730
2,LW,8.475933e+06,11.099010,14.623762,25.722772,101.950495,14.248713
1,D,8.475402e+06,3.612360,13.528090,17.140449,84.056180,18.707079

In [46]:
df.groupby('position').mean(numeric_only=True)

,player_id,goals,assists,points,shots,timeOnIcePerGame
position,,,,,,
C,8.475739e+06,11.834395,17.280255,29.114650,104.082803,15.541656
D,8.475402e+06,3.612360,13.528090,17.140449,84.056180,18.707079
LW,8.475933e+06,11.099010,14.623762,25.722772,101.950495,14.248713
RW,8.475478e+06,12.567568,15.932432,28.500000,111.000000,14.939730

In [47]:
df.groupby('position').count()

          player_id  name  goals  assists  points  shots  timeOnIcePerGame
position
C               157   157    157      157     157    157               157
D               178   178    178      178     178    178               178
LW              101   101    101      101     101    101               101
RW               74    74     74       74      74     74                74

In [48]:
df.groupby('position').min()

,player_id,name,goals,assists,points,shots,timeOnIcePerGame
position,,,,,,,
C,8466138,Adam Henrique,2,2,4,33,6.23
D,8465009,Aaron Ekblad,0,2,2,41,11.41
LW,8470257,Adam Erne,2,4,7,39,8.18
RW,8468508,Alex Chiasson,3,4,9,47,9.59

In [49]:
df.groupby('position').max()

,player_id,name,goals,assists,points,shots,timeOnIcePerGame
position,,,,,,,
C,8480144,Zemgus Girgensons,33,48,74,233,21.35
D,8480172,Zdeno Chara,13,38,47,180,24.31
LW,8479465,Zack Smith,31,42,63,217,19.80
RW,8479339,Zack Kassian,30,41,65,201,20.32

In [50]:
df.groupby('position').sum()

,player_id,name,goals,assists,points,shots,timeOnIcePerGame
position,,,,,,,
C,1330691059,Connor McDavidLeon DraisaitlNathan MacKinnonEv...,1858,2713,4571,16341,2440.04
D,1508621556,John CarlsonRoman JosiTorey KrugBrent BurnsVic...,643,2408,3051,14962,3329.86
LW,856069192,Artemi PanarinBrad MarchandJonathan HuberdeauA...,1121,1477,2598,10297,1439.12
RW,627185397,Nikita KucherovDavid PastrnakPatrick KaneMikko...,930,1179,2109,8214,1105.54

In [55]:
df.groupby('position').agg({'shots':['mean','max','min','count','sum']})

               shots
                mean  max min count    sum
position
C         104.082803  233  33   157  16341
D          84.056180  180  41   178  14962
LW        101.950495  217  39   101  10297
RW        111.000000  201  47    74   8214

In [57]:
df.groupby('position').agg({'goals':['mean','max','min','count','sum']})

              goals
               mean max min count   sum
position
C         11.834395  33   2   157  1858
D          3.612360  13   0   178   643
LW        11.099010  31   2   101  1121
RW        12.567568  30   3    74   930

In [58]:
df.groupby('position').agg({'shots':['mean','max','min','count','sum'],'goals':['mean','max','min','count','sum']})

               shots                            goals
                mean  max min count    sum       mean max min count   sum
position
C         104.082803  233  33   157  16341  11.834395  33   2   157  1858
D          84.056180  180  41   178  14962   3.612360  13   0   178   643
LW        101.950495  217  39   101  10297  11.099010  31   2   101  1121
RW        111.000000  201  47    74   8214  12.567568  30   3    74   930

In [64]:
df.groupby(['position','goals']).mean(numeric_only=True)

                   player_id    assists     points       shots  \
position goals
C        2      8.474230e+06   2.000000   4.000000   33.000000
         3      8.474291e+06   8.000000  11.000000   53.000000
         4      8.473664e+06   8.750000  12.750000   62.000000
         5      8.475043e+06   9.666667  14.666667   77.333333
         6      8.475432e+06   9.416667  15.416667   64.333333
...                      ...        ...        ...         ...
RW       21     8.477115e+06  27.500000  48.500000  138.500000
         22     8.479339e+06  22.000000  44.000000  176.000000
         23     8.474141e+06  36.000000  59.000000  200.000000
         24     8.477440e+06  33.000000  57.000000  159.000000
         30     8.477956e+06  32.000000  62.000000  201.000000

                timeOnIcePerGame
position goals
C        2              6.230000
         3             12.420000
         4             11.930000
         5             13.176667
         6             11.978333
...                          ...
RW       21            18.390000
         22            18.250000
         23            20.320000
         24            18.330000
         30            18.100000

[86 rows x 5 columns]

In [ ]:
# Added comments
df.groupby('position').describe()

         player_id                                                    \
             count          mean          std        min         25%
position
C            157.0  8.475739e+06  2711.979648  8466138.0  8474230.00
D            178.0  8.475402e+06  2642.180030  8465009.0  8474176.25
LW           101.0  8.475933e+06  2131.982951  8470257.0  8474709.00
RW            74.0  8.475478e+06  2382.759079  8468508.0  8474168.25

                                            goals             ...   shots  \
                50%         75%        max  count       mean  ...     75%
position                                                      ...
C         8476432.0  8477846.00  8480144.0  157.0  11.834395  ...  126.00
D         8475763.0  8477010.50  8480172.0  178.0   3.612360  ...   99.75
LW        8476438.0  8477476.00  8479465.0  101.0  11.099010  ...  127.00
RW        8475815.0  8477360.75  8479339.0   74.0  12.567568  ...  134.50

                timeOnIcePerGame                                             \
            max            count       mean       std    min    25%     50%
position
C         233.0            157.0  15.541656  2.745842   6.23  13.61  15.720
D         180.0            178.0  18.707079  2.902710  11.41  16.68  18.975
LW        217.0            101.0  14.248713  2.652062   8.18  12.20  14.010
RW        201.0             74.0  14.939730  2.655134   9.59  12.96  15.290


             75%    max
position
C         17.570  21.35
D         20.960  24.31
LW        16.170  19.80
RW        17.025  20.32

[4 rows x 48 columns]